title: Guía de Trabajo a Distancia
description: Una guía para gobiernos locales trabajando de manera ágil y remota.

exclude:
  - bin
  - docs
  - Gemfile*
  - node_modules
  - package.json
  - Rakefile
  - script
  - test
  - vendor

permalink: /:path/

collections:
  articles:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/cards/default.png
  - scope:
      path: ""
      type: articles
    values:
      layout: article

plugins:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: assets/css/
  style: :compressed
  load_paths:
    - node_modules

logo: /assets/images/cards/default.png

github:
  repository_nwo: https://github.com/LabLeon/gobierno-agil

twitter:
  username: lableon_

facebook:
  publisher: https://www.facebook.com/lab.leon.DGI/
